.github/workflows/cmangos-macos-build.yml

Fix MacOS CI pipeline by updating to MacOS 12

CI: TryFix MacOS CI Pipeline

---

CMakeLists.txt

Now handled in core CMake files

Remove Eluna defines

---

playerbot/PlayerbotMgr.cpp

fix linux build - convert string to char

fix linux build - convert string to char

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk

added DisableBotOptimizations to config for disabling optimizations within playerbots and cmangos core

added "DisableBotOptimizations" to config

---

playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/actions/BattleGroundJoinAction.cpp

disable "nolag" check for BG joins if sPlayerbotAIConfig.disableActivityPriorities as per @mostlikelyfr suggestion

disable "nolag" check for BG joins if sPlayerbotAIConfig.disableActivityPriorities 

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/RandomPlayerbotMgr.cpp
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk

added option to disable/enable random teleports on revive

added option to disable/enable random teleports on revive

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/actions/AcceptDuelAction.h

added option for bots to decline duels below certain level

added option for bots to decline duels below certain level

---

playerbot/PlayerbotAIConfig.cpp
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk

tweaked default reply chances for special link messages

tweaked default reply chances for special link messages

---

playerbot/PlayerbotAI.cpp
playerbot/PlayerbotAI.h
playerbot/strategy/actions/AddLootAction.cpp

fix https://github.com/cmangos/issues/issues/3750 ignore pets for hostile checks for looting

fix https://github.com/cmangos/issues/issues/3750 ignore pets for hostile checks for looting

---

playerbot/strategy/values/DeadValues.cpp

adjusted DeadValues to be more adequate

adjusted DeadValues to be more adequate

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/RandomPlayerbotMgr.cpp
playerbot/RandomPlayerbotMgr.h
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/actions/ReviveFromCorpseAction.cpp
playerbot/strategy/values/DeadValues.cpp

removed settings param AiPlayerbot.EnableRandomTeleportOnRevive
added settings params AiPlayerbot.EnableRandomTeleports, AiPlayerbot.RealisticRevives 
changed revive logic so that there is no more teleports if AiPlayerbot.RealisticRevives = 1 
disabled teleports in ProcessBot() if AiPlayerbot.EnableRandomTeleports = 0

Added options to disable ghost teleports, random teleports

---

playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk

added missing letter

---

playerbot/strategy/values/ItemUsageValue.cpp

removed trade goods check, should not have been there

removed trade goods check, should not have been there

---

playerbot/PlayerbotAIConfig.cpp
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/actions/AhAction.cpp
playerbot/strategy/actions/BuyAction.cpp
playerbot/strategy/actions/SuggestWhatToDoAction.cpp
playerbot/strategy/values/ItemUsageValue.cpp
playerbot/strategy/values/ItemUsageValue.h

craftable prices now derive from cost of crafting ingredients
adjustments to logic of which items bots should sell at ah
added a bunch of cached collections to conveniently take data from 
changed AiPlayerbot.ShouldQueryAHForItemMedianPrice default to false

Adjusted price calculations, should be very realistic now

---

playerbot/strategy/values/ItemUsageValue.cpp
playerbot/strategy/values/ItemUsageValue.h

removed useless variables and methods as well as their usages

removed useless variables and methods as well as their usages

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/actions/AhAction.h
playerbot/strategy/values/ItemUsageValue.cpp
playerbot/strategy/values/ItemUsageValue.h

added GetLowestAcceptableAHBuyoutPrice() method for convenience
added checks if current AH listings are too cheap to even bother 
added GetAHListingLowestBuyoutPrice() which queries lowest AH buyout price listing 
changed AiPlayerbot.ShouldQueryAHForItemMedianPrice to AiPlayerbot.ShouldQueryAHListingsOutsideOfAH in config

Improved logic which determines whether bot should sell item to AH or vendor, changed config value

---

playerbot/strategy/actions/SayAction.cpp
sql/world/ai_playerbot_texts.sql

added bot->GetGroup() checks when replying to LFG/LFM
added new texts for bots to reply when they have quests but they are in group

added new texts for bots to reply when they have quests but they are in group

---

playerbot/strategy/values/ItemUsageValue.cpp

added missing return statement
renamed lowestAhBuyoutPrice to lowestAhItemListingBuyoutPrice

fix for ah logic

---

playerbot/strategy/actions/DebugAction.cpp
playerbot/strategy/values/ItemUsageValue.cpp
playerbot/strategy/values/ItemUsageValue.h

updated method names to more clearly reflect logic 
added debug out and updated debug texts as well

changed lowest price SQL query to return price per item

---

playerbot/PlayerbotAI.cpp
playerbot/PlayerbotAI.h
playerbot/strategy/values/ItemUsageValue.cpp

added GetEquippedAnyBags() GetEquippedQuivers() methods

added ilvl and quality checks for quivers for hunters

---

playerbot/strategy/actions/AhAction.cpp
playerbot/strategy/actions/DebugAction.cpp
playerbot/strategy/values/ItemUsageValue.cpp
playerbot/strategy/values/ItemUsageValue.h

divided ahsellprice to two min and max methods
added IsItemSoldByAnyVendorButHasLimitedMaxCount() added IsWorthBuyingFromAhToResellAtAH()
improved pricing logic
improved debug outs for ah

improved ah pricing logic

---

playerbot/strategy/actions/BattleGroundJoinAction.cpp
playerbot/strategy/actions/BattleGroundJoinAction.h

added check if party members can join BG too to avoid wrong levels in BG

added check if party members can join BG too to avoid wrong levels in BG

---

playerbot/strategy/values/ItemUsageValue.cpp

increased price multiplier for basePrice and lowered AHMaxSell price slightly

increased price multiplier for basePrice and lowered AHMaxSell price slightly

---

playerbot/strategy/actions/CheckMountStateAction.cpp
playerbot/strategy/actions/ReleaseSpiritAction.h
playerbot/strategy/actions/ReviveFromCorpseAction.cpp
playerbot/strategy/values/DeadValues.cpp

Changed repop action logic
Added logs for obviously wrong situations

Changed revive logic to more adequate

---

playerbot/strategy/values/ItemUsageValue.cpp

added check for extra cheap trash misc armor and recipe class that may require skill (just in case)

added check for extra cheap trash misc armor and recipe class that may require skill (just in case)

---

playerbot/PlayerbotAIConfig.cpp
playerbot/PlayerbotAIConfig.h
playerbot/aiplayerbot.conf.dist.in
playerbot/aiplayerbot.conf.dist.in.tbc
playerbot/aiplayerbot.conf.dist.in.wotlk
playerbot/strategy/values/FreeMoveValues.cpp

separated additional config value - AiPlayerbot.MaxFreeMoveDistance
added config value AiPlayerbot.FreeMoveDelay to control delay after which bots in group will start freely roaming around master

Added configs to control bot behavior (this should have been there all along)

---

playerbot/strategy/values/DeadValues.cpp

added fallback to self graveyard if best graveyard is not found
added logs to graveyard values

fix travel graveyards not being found a lot of the time (fallback to self graveyard)

---

playerbot/strategy/values/ItemUsageValue.cpp

added check for limited supply scrolls - they are not worth buying to resell at AH or just sell at AH

added check for limited supply scrolls - they are not worth buying to resell at AH or just sell at AH

---

playerbot/strategy/actions/AhAction.cpp

added IsMoreProfitableToSellToAHThanToVendor() check before posting an item to AH

added IsMoreProfitableToSellToAHThanToVendor() check before posting an item to AH

---

playerbot/strategy/values/ItemUsageValue.cpp

improved logic that decides whether an item is worth equipping as upgrade

improved logic that decides whether an item is worth equipping as upgrade

---

playerbot/PlayerbotFactory.cpp
playerbot/RandomItemMgr.cpp
playerbot/TravelNode.cpp
playerbot/WorldPosition.cpp
playerbot/strategy/actions/AutoLearnSpellAction.cpp
playerbot/strategy/triggers/StuckTriggers.h
playerbot/strategy/values/QuestValues.cpp

Updates playerbot code for the weak_ptr additions from the core sync.

Playerbot changes for weak_ptr

---

playerbot/strategy/warrior/ProtectionWarriorStrategy.cpp

Improves arms specced bots with protection strategies enabled.

Added Mortal Strike into protection rotation

---

playerbot/PlayerbotCommandServer.cpp

Boost: Add 1.87 support

---

playerbot/ServerFacade.h
playerbot/WorldPosition.cpp
playerbot/WorldPosition.h
playerbot/strategy/actions/BattleGroundTactics.cpp
playerbot/strategy/values/NearestGameObjects.cpp
playerbot/strategy/values/NearestGameObjects.h
playerbot/strategy/values/ValueContext.h

+ Implement static los check instead, which is sufficient for almost all cases

Battleground: Fix flag game objects not being detected due to dynamic LOS issues

---

playerbot/strategy/actions/BattleGroundTactics.cpp
playerbot/strategy/actions/BattleGroundTactics.h

This reverts commit f45a754c7834fe4f8a4286b58a349bece794025c.

Revert "Bg: Removed some wip methods"

---

playerbot/RandomPlayerbotMgr.cpp

as the title says.
Please check if the added BeginTransaction and CommitTransaction interferes with other ongoing transactions.

SQL: Made some queries more readable

---

playerbot/strategy/shaman/ElementalShamanStrategy.cpp
playerbot/strategy/shaman/EnhancementShamanStrategy.cpp
playerbot/strategy/shaman/RestorationShamanStrategy.cpp

Replaced non-stackable weapon enchant totems with more appropriate ones by default.

Shaman: Default totem logic tweak

---

playerbot/strategy/shaman/ShamanActions.h

Better control for grace of air, wrath of air and windfury totems while grouped.

Shaman: Air totem tweaks

---

playerbot/strategy/warrior/ArmsWarriorStrategy.cpp
playerbot/strategy/warrior/FuryWarriorStrategy.cpp

More reliable use of Charge when out of melee range

Warrior: Charge tweak
